# Generated by Django 6.0.6 on 2026-06-06 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='Empresa')),
                ('rut', models.CharField(blank=True, default='', max_length=12, unique=True, verbose_name='RUT')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Contacto principal')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20, verbose_name='Plan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_users', models.ManyToManyField(blank=True, related_name='client_portals', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios del portal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=200, verbose_name='Nombre del equipo')),
                ('friendly_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre amigable')),
                ('agent_token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token del agente')),
                ('device_type', models.CharField(choices=[('workstation', 'Workstation'), ('server', 'Servidor'), ('laptop', 'Laptop'), ('printer', 'Impresora'), ('network', 'Equipo de Red'), ('other', 'Otro')], default='workstation', max_length=20, verbose_name='Tipo')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistema operativo')),
                ('os_version', models.CharField(blank=True, max_length=200, verbose_name='Versión SO')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP local')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Último contacto')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['client', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='M365Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100, verbose_name='Tenant ID (Azure AD)')),
                ('azure_client_id', models.CharField(max_length=100, verbose_name='Client ID (App Registration)')),
                ('azure_client_secret', models.CharField(max_length=300, verbose_name='Client Secret')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('sync_error', models.TextField(blank=True, verbose_name='Último error de sync')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='m365_tenant', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tenant M365',
                'verbose_name_plural': 'Tenants M365',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Severidad')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.client', verbose_name='Cliente')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.hardwaredevice')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=253, verbose_name='Dominio')),
                ('registrar', models.CharField(blank=True, max_length=200, verbose_name='Registrador')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovación automática')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Última verificación')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Por vencer (< 90 días)'), ('critical', 'Crítico (< 30 días)'), ('expired', 'Vencido'), ('unknown', 'Desconocido')], default='unknown', max_length=20, verbose_name='Estado')),
                ('resolves_dns', models.BooleanField(default=True, verbose_name='Resuelve DNS')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
                'ordering': ['expiry_date'],
                'unique_together': {('client', 'fqdn')},
            },
        ),
        migrations.CreateModel(
            name='M365License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_part_number', models.CharField(max_length=100, verbose_name='SKU')),
                ('friendly_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del producto')),
                ('total_licenses', models.IntegerField(default=0, verbose_name='Total')),
                ('consumed_licenses', models.IntegerField(default=0, verbose_name='Usadas')),
                ('capability_status', models.CharField(choices=[('Enabled', 'Activa'), ('Suspended', 'Suspendida'), ('Warning', 'Advertencia'), ('LockedOut', 'Bloqueada')], default='Enabled', max_length=50, verbose_name='Estado')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m365_licenses', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Licencia M365',
                'verbose_name_plural': 'Licencias M365',
                'ordering': ['friendly_name'],
                'unique_together': {('client', 'sku_part_number')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(verbose_name='Año')),
                ('period_month', models.IntegerField(verbose_name='Mes')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('ready', 'Listo'), ('sent', 'Enviado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Archivo PDF')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('summary_data', models.JSONField(default=dict, verbose_name='Datos del resumen')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reporte mensual',
                'verbose_name_plural': 'Reportes mensuales',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('client', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(verbose_name='Capturado')),
                ('cpu_percent', models.FloatField(default=0, verbose_name='CPU %')),
                ('ram_used_percent', models.FloatField(default=0, verbose_name='RAM %')),
                ('ram_total_gb', models.FloatField(default=0, verbose_name='RAM total (GB)')),
                ('disk_usage', models.JSONField(default=list, verbose_name='Discos')),
                ('uptime_seconds', models.BigIntegerField(default=0, verbose_name='Uptime (s)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.hardwaredevice')),
            ],
            options={
                'ordering': ['-captured_at'],
                'get_latest_by': 'captured_at',
                'indexes': [models.Index(fields=['device', '-captured_at'], name='core_teleme_device__10b567_idx'), models.Index(fields=['-captured_at'], name='core_teleme_capture_c20e36_idx')],
            },
        ),
    ]
