# Generated by Django 6.0.6 on 2026-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Núcleos físicos'),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='cpu_freq_mhz',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU Freq (MHz)'),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='cpu_threads',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hilos lógicos'),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='network',
            field=models.JSONField(default=dict, verbose_name='Red'),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='temperatures',
            field=models.JSONField(default=list, verbose_name='Temperaturas'),
        ),
    ]
