# Generated by Django 6.0.6 on 2026-06-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telemetrysnapshot_cpu_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceincident',
            name='category',
            field=models.CharField(choices=[('hardware', 'Hardware / Equipo'), ('domain', 'Dominio'), ('email', 'Email / SMTP'), ('license', 'Licencia M365'), ('network', 'Red'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='maintenanceincident',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Notificar por email'),
        ),
    ]
