# Generated by Django 6.0.6 on 2026-06-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_client_telegram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_timesta_189a84_idx',
            old_name='core_audit_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='alert_emails',
            field=models.TextField(blank=True, help_text='Un email por línea. Recibirán todas las alertas y verificaciones del cliente.', verbose_name='Emails adicionales para alertas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID donde se enviarán alertas críticas vía Telegram (equipos sin conexión, anomalías de seguridad críticas, viaje imposible, certificados SSL por vencer). Deja vacío para desactivar. Ver guía de configuración.', max_length=64, verbose_name='Chat ID de Telegram'),
        ),
        migrations.AlterField(
            model_name='m365tenant',
            name='known_countries',
            field=models.JSONField(blank=True, default=list, help_text='Países desde los que se ha iniciado sesión anteriormente (baseline). Se actualiza automáticamente.', verbose_name='Países conocidos'),
        ),
        migrations.AlterField(
            model_name='m365tenant',
            name='sender_mailbox',
            field=models.EmailField(blank=True, help_text='Buzón del tenant desde el que se envía el email de verificación. Ej: it@vcchile.cl — debe ser un usuario con licencia Exchange activa.', max_length=254, verbose_name='Buzón remitente (sendMail)'),
        ),
        migrations.AlterField(
            model_name='m365tenant',
            name='verify_email',
            field=models.EmailField(blank=True, help_text='Email al que se enviará el test de envío en cada verificación. Si está vacío, no se envía el email de prueba.', max_length=254, verbose_name='Email de destino para verificación'),
        ),
        migrations.AlterField(
            model_name='usertotp',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
