# Generated by Django 6.0.6 on 2026-06-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_network_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityanomalyevent',
            name='anomaly_type',
            field=models.CharField(choices=[('new_admin', 'Nuevo administrador local'), ('removed_admin', 'Administrador local eliminado'), ('new_startup', 'Nuevo programa de inicio'), ('removed_startup', 'Programa de inicio eliminado'), ('new_task', 'Nueva tarea programada'), ('removed_task', 'Tarea programada eliminada'), ('new_software', 'Nuevo software instalado'), ('removed_software', 'Software desinstalado'), ('open_wifi', 'Red WiFi abierta (sin cifrado)'), ('firewall_off', 'Firewall desactivado'), ('network_change', 'Cambio de red'), ('dns_change', 'Cambio de servidores DNS')], max_length=20, verbose_name='Tipo'),
        ),
    ]
