# Generated by Django 5.2.15 on 2026-06-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_securityanomalyevent_anomaly_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
