# Generated by Django 5.2.15 on 2026-06-26 18:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0032_securityscoresnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario cliente',
                'verbose_name_plural': 'Usuarios cliente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
