# Generated by Django 5.2.15 on 2026-06-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_portaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='snmp', max_length=8)),
                ('model_description', models.CharField(blank=True, max_length=255)),
                ('device_status', models.CharField(blank=True, max_length=32)),
                ('status_label', models.CharField(blank=True, max_length=120)),
                ('error_states', models.JSONField(blank=True, default=list)),
                ('supplies', models.JSONField(blank=True, default=list)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(default='unknown', max_length=16)),
                ('risk_reasons', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_snapshot', to='core.hardwaredevice')),
            ],
            options={
                'verbose_name': 'Snapshot de impresora',
                'verbose_name_plural': 'Snapshots de impresora',
            },
        ),
    ]
