# Generated by Django 6.0.6 on 2026-06-07 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Verificado')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('timeout', 'Timeout'), ('error', 'Error')], max_length=10, verbose_name='Estado')),
                ('response_ms', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de respuesta (ms)')),
                ('error_msg', models.TextField(blank=True, verbose_name='Error')),
                ('smtp_host', models.CharField(max_length=200, verbose_name='Host SMTP')),
                ('smtp_port', models.IntegerField(verbose_name='Puerto SMTP')),
            ],
            options={
                'verbose_name': 'Verificación SMTP',
                'verbose_name_plural': 'Verificaciones SMTP',
                'ordering': ['-checked_at'],
                'get_latest_by': 'checked_at',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinatario')),
                ('subject', models.CharField(max_length=500, verbose_name='Asunto')),
                ('category', models.CharField(choices=[('report', 'Reporte mensual'), ('alert', 'Alerta de vencimiento'), ('incident', 'Notificación de incidente'), ('test', 'Email de prueba'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Error'), ('bounced', 'Rebotado')], default='sent', max_length=10, verbose_name='Estado')),
                ('error_msg', models.TextField(blank=True, verbose_name='Error')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.client')),
            ],
            options={
                'verbose_name': 'Email enviado',
                'verbose_name_plural': 'Emails enviados',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='emailmon_em_sent_at_df7fdf_idx')],
            },
        ),
    ]
